@startuml
!include ../clean.skin

frame "Exasol Database" {
    !include COMPONENT(ExasolCore)
    !include INTERFACE(AdapterRequest)
}

frame "Virtal Schema" {
    component JdbcAdapter {
        component DB2DqlDialect
        component ExasolSqlDialect
        component GenericSqlDialect
        component HiveSqlDialect
        component ImpalaSqlDialect
        component "...Dialect"
    }
    component VirtualSchemaCore
    
    JdbcAdapter -u-> VirtualSchemaCore
}


ExasolCore -u-() AdapterRequest
JdbcAdapter -l-( AdapterRequest

@enduml