@startuml
!include ../clean.skin

frame "Exasol Database" {
    !include COMPONENT(ExasolCore)
    !include INTERFACE(AdapterRequest)
}

frame "Virtal Schema" {
    component VirtualSchemaCore
    interface VirtualSchemaAdapter <<interface>>
    VirtualSchemaCore -d-( VirtualSchemaAdapter
}

frame "Postgres Virtual Schema" {
    component PostgresVirtualSchema
}

frame "GitHub Virtual Schema" {
    component GitHubVirtualSchema
}

ExasolCore -u-() AdapterRequest
VirtualSchemaCore -l-( AdapterRequest
PostgresVirtualSchema -u-() VirtualSchemaAdapter
GitHubVirtualSchema -u-() VirtualSchemaAdapter

@enduml