@startuml
!include ../exasol.skin

database "ExasolDatabase"
database "DataSource"  <<external>>


node "Java Virtual Machine" as JVMB {
    component "DataSourceJdbcDriver" as DataSourceJdbcDriverExaOp  <<external>>
}

interface "Virtual\nSchemaAPI" as VirtualSchemaAPI
component "VirtualSchemaFrontend"

storage "ExaOperationFileSystem" {
    artifact "xyz-jdbc-driver.jar" as JdbcDriverJarExaOp <<external>>
}

VirtualSchemaFrontend -u-> ExasolDatabase
VirtualSchemaFrontend -d-> "0 .. *  " DataSourceJdbcDriverExaOp
JdbcDriverJarExaOp .u.> DataSourceJdbcDriverExaOp

storage "BucketFS" {
    artifact "xyz-jdbc-driver.jar" as JdbcDriverJar  <<external>>
    artifact "virtualschema-jdbc-\nadapter-dist-1.15.1.jar" as VirtualSchemaJar
    
    JdbcDriverJar -[hidden]u- VirtualSchemaJar
}

node "UDFContainer" {
    node "Java Virtual Machine" as JVMA {
        component "VirtualSchemaBackend"
        component "DataSourceJdbcDriver"  <<external>>
        VirtualSchemaBackend -d-> DataSourceJdbcDriver
    }
}

VirtualSchemaBackend -r- VirtualSchemaAPI
VirtualSchemaFrontend -r-( VirtualSchemaAPI
VirtualSchemaJar .r.> VirtualSchemaBackend
JdbcDriverJar .r.> DataSourceJdbcDriver
DataSourceJdbcDriver --> DataSource
DataSourceJdbcDriverExaOp -d-> DataSource

@enduml