@startuml
!include ../clean.skin

together {
    class RequestDispatcher {
      + {static} adapterCall(metadata : ExaMetadata, rawRequest : String) : String
    }
    
    class AdapterRegistry {
        + getAdapterForName(name : String) : VirtualSchemaAdapter
    }
}

interface VirtualSchemaAdapter <<interface>> [[java:com.exasol.adapter.VirtualSchemaAdapter]]  {
    + createVirtualSchema(metadata : ExaMetadata, request : CreateVirtualSchemaRequest) : CreateVirtualSchemaResponse
    + dropVirtualSchema(metadata : ExaMetadata, request : DropVirtualSchemaRequest) : DropVirtualSchemaResponse
    + refresh(metadata : ExaMetadata, request : RefreshRequest) : RefreshResponse
    + setProperties(metadata : ExaMetadata, request : SetPropertiesRequest) : SetPropertiesResponse
    + getCapabilities(metadata : ExaMetadata, request : GetCapabilitiesRequest) : GetCapabilitiesResponse
    + pushdown(metadata : ExaMetadata, request : PushDownRequest) : PushDownResponse
}

class VirtualSchemaPostgresAdapter

class RequestParser

class ResponseJsonConverter

RequestDispatcher -u-> ResponseJsonConverter : turn repsonse\ninto JSON
RequestDispatcher -u-> RequestParser : parse raw request
RequestDispatcher -r-> AdapterRegistry : find\nresponsible\nadapter
RequestDispatcher -d-> VirtualSchemaAdapter : dispatch request
VirtualSchemaPostgresAdapter .u.|> VirtualSchemaAdapter
AdapterRegistry --> VirtualSchemaAdapter

@enduml