@startuml
!include ../exasol.skin

together {
    class RequestDispatcher
    class AdapterRegistry
}

interface VirtualSchemaAdapter <<interface>>
class RequestParser
class ResponseJsonConverter
interface AdapterFactory <<interface>>

frame "Adapter Plug-in" {
    class JdbcAdapter
    class JdbcAdapterFactory
}

RequestDispatcher -u-> ResponseJsonConverter : turn repsonse into JSON
RequestDispatcher -u-> RequestParser : parse raw request
RequestDispatcher -r-> AdapterRegistry : find responsible adapter
RequestDispatcher -d-> VirtualSchemaAdapter : dispatch request
JdbcAdapter .u.|> VirtualSchemaAdapter
AdapterRegistry --> AdapterFactory : load
AdapterRegistry --> AdapterFactory : create adapter instance
JdbcAdapterFactory .u.|> AdapterFactory
JdbcAdapterFactory -l-> JdbcAdapter : <<create>>

@enduml