@startuml
!include ../clean.skin

class JdbcAdapter

class SqlDialectFactory {
    + createSqlDialect(connection : Connection, properties: AdapterProperties, dialectRegistry : SqlDialectRegistry) : SqlDialect
    + getSqlDialectName() : String
}

interface SqlDialect

abstract class AbstractSqlDialect {
    + AbstractSqlDialect(connection: Connection, properties : AdapterProperties)
}

class PostgreSQLSqlDialect

JdbcAdapter -d-> SqlDialectFactory
note on link
    inject JDBC connection and
    user-defined properties
end note
SqlDialectFactory -d-> SqlDialect : <<create>>
note on link
    inject JDBC connection and
    user-defined properties
end note
AbstractSqlDialect .u.|> SqlDialect
PostgreSQLSqlDialect -u-|> AbstractSqlDialect

@enduml