@startuml
!include ../exasol.skin

JdbcAdapter -r-> SqlDialectFactory
note on link
    inject JDBC connection,
    adapter registry and
    user-defined properties
end note

SqlDialectFactory -d-> SqlDialect : <<create>>
note on link
    inject JDBC connection and
    user-defined properties
end note

AbstractSqlDialect .u.|> SqlDialect
AthenaSqlDialect -u-|> AbstractSqlDialect
DB2SqlDialect -u-|> AbstractSqlDialect
ExasolSqlDialect -u-|> AbstractSqlDialect
TeradataSqlDialect -u-|> AbstractSqlDialect

@enduml